version: "2"

linters:
  default: standard
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-dirs:
    - testdata
